[tool.poetry]
name = "client"
version = "0.1.0"
description = ""
authors = ["Eric Chen <eric@sahale.io>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
cakework = "^0.0.45"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
